apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: master-laravel-oci
  namespace: master
spec:
  url: oci://ghcr.io/steven-streller/charts
  type: oci
  interval: 10m