apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  releaseName: vault
  chart:
    spec:
      chart: vault
      version: "0.30.1"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
  interval: 5m
  values:
    ui:
      enabled: true